name: Build / Test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
  push:
    paths:
      - "src/**"
      - "tests/**"
    branches:
      - develop
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.3"

      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v4.3.0

      - name: Install Luacheck
        run: luarocks install luacheck

      - run: luacheck src tests/unit

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm test:integration

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out repository code

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.3" # Specify the Lua version you need

      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v4.3.0

      - name: Install Lua Dependencies
        run: luarocks make ar-io-marketplace-process-0.1.0-1.rockspec

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install Node Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Busted Tests
        run: pnpm test:unit

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/luacov.report.out
