/**
 * Temporary workaround for ao-localnet SDK missing from the GitHub package.
 * Reads configuration directly from the .ao-localnet.config.json file.
 */

import { readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { connect, createDataItemSigner } from '@permaweb/aoconnect';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Path to the ao-localnet config file
const CONFIG_PATH = join(__dirname, '../../node_modules/ao-localnet/.ao-localnet.config.json');

interface LocalnetConfig {
  urls: {
    gateway: string;
    graphql: string;
    mu: string;
    su: string;
    cu: string;
    bundler: string;
  };
  bootstrap: {
    transactions: {
      scheduler: string;
      module: string;
      aosModule: string;
      schedulerLocation: string;
    };
  };
  wallets: {
    aoWallet: string;
  };
}

let config: LocalnetConfig | null = null;

function loadConfig(): LocalnetConfig {
  if (!config) {
    const configData = readFileSync(CONFIG_PATH, 'utf-8');
    config = JSON.parse(configData);
  }
  return config!;
}

export function getUrls() {
  const cfg = loadConfig();
  return cfg.urls;
}

export function getScheduler() {
  const cfg = loadConfig();
  const scheduler = cfg.bootstrap.transactions.scheduler;
  if (!scheduler) {
    throw new Error(
      'Scheduler not found in config. Please run: npx ao-localnet configure && npx ao-localnet seed'
    );
  }
  return scheduler;
}

export function getAosModule() {
  const cfg = loadConfig();
  const module = cfg.bootstrap.transactions.aosModule;
  if (!module) {
    throw new Error(
      'AOS module not found in config. Please run: npx ao-localnet configure && npx ao-localnet seed'
    );
  }
  return module;
}

export function getAuthority() {
  // For localnet, authority is typically the MU wallet address
  // We'll read this from the ao-wallet.json
  return getAoWalletAddress();
}

export function getAoWallet() {
  const cfg = loadConfig();
  // Use the wallet generated by ao-localnet configure/seed
  const walletPath = join(__dirname, '../../node_modules/ao-localnet', cfg.wallets.aoWallet);
  
  try {
    const walletData = readFileSync(walletPath, 'utf-8');
    return JSON.parse(walletData);
  } catch (error: any) {
    throw new Error(
      `Failed to load AO wallet from ${walletPath}. ` +
      'Please run: npx ao-localnet configure\n' +
      `Original error: ${error.message}`
    );
  }
}

let cachedWalletAddress: string | null = null;

async function computeWalletAddress(): Promise<string> {
  const wallet = getAoWallet();
  // Dynamically import arweave to avoid issues
  const Arweave = (await import('arweave')).default;
  const arweave = Arweave.init({});
  return await arweave.wallets.jwkToAddress(wallet);
}

function getAoWalletAddress(): string {
  // Return a placeholder - this gets computed properly in the async getAuthorityAddress export
  // The sync version is only used for backwards compatibility
  return '';
}

// Async version that properly computes the wallet address
export async function getAuthorityAddress(): Promise<string> {
  if (cachedWalletAddress) {
    return cachedWalletAddress;
  }
  cachedWalletAddress = await computeWalletAddress();
  return cachedWalletAddress;
}

export function getAoInstance() {
  const urls = getUrls();
  return connect({
    MU_URL: urls.mu,
    CU_URL: urls.cu,
    GATEWAY_URL: urls.gateway,
  });
}

export function createAoSigner() {
  const wallet = getAoWallet();
  return createDataItemSigner(wallet);
}

